### ISSUE TITLE
On download complete callback

### ISSUE THREAD

**Issue by ashl1** [PixelsCommander/Download-File-JS#10]
What about download complete callback?
I found that using iframe (like in fork https://github.com/Nannakuhtum/Download-File-JS/commit/6dcc704751af09eecbee9341102a2e86191c0383) its possible to listen on "load" window event, but what about virtual link clicking?

**Comment by PixelsCommander** [comment]
Does not load mean "started", but not "finished"? 

Really I do not think listening for loading end is feasible. However you may have a look at xhr2 etc.

**Comment by ashl1** [comment]
If the file cannot be loaded (with error for example) it means the loading is finished but with error. Like AJAX ('success', 'error' or 'complete' with both meaning).
It's not a good idea not to implement this just in that case we cannot tell the user if file downloads long time (if required for prepare, for example).
