### ISSUE TITLE
How to name the file?

### ISSUE THREAD

**Issue by red010182** [PixelsCommander/Download-File-JS#8]
Hi

I'm using downloadFile on a video stream, but I don't know how to name the file. I have no control of that stream, it's from 3rd party, so I can't set filename on header.

Any help would be very appreciated.

**Comment by PixelsCommander** [comment]
You can not download stream as a file. You should use specialized libraries
for that.

2015-03-04 8:54 GMT+01:00 tpy notifications@github.com:
